name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        working-directory: ./ANGULARCRUD
        run: npm install && npm run gh-build && cp dist/ANGULARCRUD/index.html dist/ANGULARCRUD/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master # The branch the action should deploy to.
          folder: ANGULARCRUD/dist/ANGULARCRUD # The folder the action should deploy.
